site_name: Asking Right Questions 
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    scheme: default
    accent: deep purple
    toggle:
      icon: material/brightness-auto
      name: "Switch to light mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    accent: amber
    toggle:
      icon: material/brightness-2
      name: "Switch to system theme"
  - media: "(prefers-color-scheme: light)"
    scheme: default
    accent: deep purple
    toggle:
      icon: material/brightness-5
      name: "Switch to dark mode"
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
plugins:
  - search
